// <auto-generated />
// Run: dotnet ef migrations add InitialCreate
// Then: dotnet ef database update
//
// This file is a placeholder. Generate the real migration by running:
//   cd backend/Fabric.API
//   dotnet ef migrations add InitialCreate
//   dotnet ef database update
//
// Railway runs `dotnet ef database update` automatically via Program.cs (db.Database.Migrate())

namespace Fabric.API.Data.Migrations;

// Migration files are generated by EF Core tooling.
// After cloning, run: dotnet ef migrations add InitialCreate
