FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Fabric.API.csproj .
RUN dotnet restore Fabric.API.csproj

COPY . .
RUN dotnet publish Fabric.API.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_ENVIRONMENT=Production

CMD ASPNETCORE_URLS="http://+:${PORT:-8080}" dotnet Fabric.API.dll
